import {
  Code,
  Network,
  FileText,
  BookOpen,
  Wrench,
  Monitor,
  Terminal,
  Globe,
  Database,
  Cloud,
  Smartphone,
  Server,
  Shield,
  GitBranch,
  Layers,
  Cpu,
  Palette,
  FlaskConical,
  Puzzle,
  Package,
  Braces,
  Bug,
  Lock,
  Wifi,
  GraduationCap,
  Presentation,
  Calculator,
  Video,
  Image,
  Map,
  Link,
  Rocket,
  Zap,
  Target,
  Users,
  Tag as TagIconDefault,
} from "@lucide/vue";
import type { Component } from "vue";

export const TAG_ICONS: Record<string, Component> = {
  code: Code,
  network: Network,
  "file-text": FileText,
  book: BookOpen,
  wrench: Wrench,
  monitor: Monitor,
  terminal: Terminal,
  globe: Globe,
  database: Database,
  cloud: Cloud,
  smartphone: Smartphone,
  server: Server,
  shield: Shield,
  "git-branch": GitBranch,
  layers: Layers,
  cpu: Cpu,
  palette: Palette,
  "flask-conical": FlaskConical,
  puzzle: Puzzle,
  package: Package,
  braces: Braces,
  bug: Bug,
  lock: Lock,
  wifi: Wifi,
  "graduation-cap": GraduationCap,
  presentation: Presentation,
  calculator: Calculator,
  video: Video,
  image: Image,
  map: Map,
  link: Link,
  rocket: Rocket,
  zap: Zap,
  target: Target,
  users: Users,
};

export const TAG_ICON_DEFAULT = TagIconDefault;

export const TAG_ICON_OPTIONS = Object.keys(TAG_ICONS);
